<a href="https://colab.research.google.com/github/nkrupiy/scratches/blob/master/homework1_%D0%9A%D1%80%D1%83%D0%BF%D0%B8%D0%B9_%D0%9D%D0%B8%D0%BA%D0%BE%D0%BB%D0%B0%D0%B9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Домашнее задание 1
### Основы Python и пакет NumPy
---


In [1]:
import numpy as np
import random
import scipy.stats as sps

### Задача 1
В первой задаче вам предлагается перемножить две матрицы двумя способами -- без использования пакета ***numpy*** и с ним. Использовать матричное произведение.

In [9]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов 
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j), здесь i -- число строк,
# j -- число столбцов.
a = np.random.sample((100,1000))
b = np.random.sample((1000,100))
a, b
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
(
a.ndim, a.shape,
b.ndim, b.shape,
)
# ========

(2, (100, 1000), 2, (1000, 100))

In [ ]:
def mult(a, b):
    # здесь напишите перемножение матриц без 
    # использования NumPy и выведите результат 

In [12]:
def np_mult(a, b):
    # здесь напишите перемножение матриц с
    # использованием NumPy и выведите результат
    return np.dot(a, b)
np_mult(a, b)

array([[242.95861553, 241.72382657, 239.58706875, ..., 245.18969728,
        239.09010938, 236.97191043],
       [247.94240877, 248.65590417, 245.39817886, ..., 250.41498039,
        240.98097397, 237.09217893],
       [256.23114896, 256.86965952, 252.57979652, ..., 260.05754879,
        251.35129006, 245.76165546],
       ...,
       [242.80860331, 251.57358949, 242.71126634, ..., 254.12000515,
        245.17691851, 245.54150387],
       [252.31052763, 254.79305783, 249.21983881, ..., 259.98395299,
        246.80069122, 243.85164493],
       [248.9169139 , 245.06328898, 241.21220887, ..., 244.77342533,
        241.13565398, 233.09376372]])

In [ ]:
# Превратим матрицы в листы, чтобы протестировать функцию без np
a_list = [[x for x in row] for row in a]
b_list = [[x for x in row] for row in b]
a_list, b_list

In [ ]:
%%time
# засечем время работы функции без NumPy
mult(a_list, b_list)

In [ ]:
%%time
# засечем время работы функции с NumPy
np_mult(a, b)

### Задача 2
Напишите функцию, которая по данной последовательности $\{A_i\}_{i=1}^n$ строит последовательность $S_n$, где $S_k = \frac{A_1 + ... + A_k}{k}$.  
Аналогично -- с помощью библиотеки **NumPy** и без нее. Сравните скорость, объясните результат.

In [31]:
np.array?

In [50]:
# функция, решающая задачу с помощью NumPy
def sec_av(A):
    # Ваш код здесь
    A = np.array(A)
    n = len(A)
    # print(f"{{Ai}}[i=1:n={n}] =", A)
    S = np.array(range(n), float)
    for k in range(1, n+1):
        sum_A1k = 0
        for i in range(k): sum_A1k += A[i]
        S[i] = sum_A1k / k
    return S

A = [1, 2, 3]
A_list = list(A)

A_list \
, sec_av(A_list)

([1, 2, 3], array([1. , 1.5, 2. ]))

In [51]:
# функция без NumPy
def stupid_sec_av(A):
    # Ваш код здесь
    n = len(A)
    # print(f"{{Ai}}[i=1:n={n}] =", A)
    S = []
    for k in range(1, n+1):
        sum_A1k = 0
        for i in range(k): sum_A1k += A[i]
        S += [sum_A1k / k]
    return S

# A = sps.uniform.rvs(size=3) #10 ** 6) 
A = [1, 2, 3]
A_list = list(A)

A_list \
, stupid_sec_av(A_list)

([1, 2, 3], [1.0, 1.5, 2.0])

In [ ]:
e = 6

# зададим некоторую последовательность и проверим ее на ваших функциях. 
# Первая функция должна работать ~ в 50 раз быстрее
A = sps.uniform.rvs(size=10 ** e) 
A_list = list(A)

%time S1 = sec_av(A)
%time S2 = stupid_sec_av(A_list)
#проверим корректность:
np.abs(S1 - S2).sum()
# S2

### Задача 3

Пусть задан некоторый массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все элементы с четными индексами исходного массива нужно возвести в куб и записать в обратном порядке относительно позиций этих элементов. Массив $X$ при этом должен остаться без изменений. В конце требуется слить (конкатенировать) массив X с преобразованным X и вывести в обратном порядке. 

In [95]:
Y = np.array([None] * len(X), float)
# Y.sort_values?
np.concatenate?

In [91]:
# a = np.array([[1, 2], [3, 4]], float)
# b = np.array([[5, 6], [7,8]], float)
a = np.array([1, 2, 3, 4], float)
b = np.array([5, 6, 7, 8], float)
np.concatenate((a,b)), \
a.shape, b.shape, 

(array([1., 2., 3., 4., 5., 6., 7., 8.]), (4,), (4,))

In [110]:
X = [0, 1, 2, 3]

In [113]:
# функция, решающая задачу с помощью NumPy
def transformation(X, a=1):
    # Ваш код здесь
    X = np.array(X)
    Y = np.array([0] * len(X))
    for i in range(len(X)):
        Y[-i-1] = X[i]**3 if i % 2 else a
    # Z = np.concatenate((X, Y))
    return np.concatenate((X, Y))[::-1]
# X, \ 
transformation(X, a=1)

array([ 1,  1,  1, 27,  3,  2,  1,  0])

In [111]:
# функция, решающая задачу  без NumPy
def stupid_transformation(X, a=1):
    # Ваш код здесь
    Y = [None] * len(X)
    for i, item in enumerate(X):
        # print(i % 2)
        Y[-i-1] = item**3 if i % 2 else a
    # Y = X + Y
    # Y.sort(reverse=True)
    return (X + Y)[::-1]
# X, \
stupid_transformation(X, a=1)    

[1, 1, 1, 27, 3, 2, 1, 0]

In [116]:
X = sps.uniform.rvs(size=10 ** 3)
X_list = list(X)
# здесь код эффективнее примерно в 20 раз. 
# если Вы вдруг соберетесь печатать массив без np -- лучше сначала посмотрите на его размер
%time S1 = transformation(X)
%time S2 = stupid_transformation(X_list)
# проверим корректность:
print(np.abs(S1 - S2).sum())

CPU times: user 1.13 ms, sys: 0 ns, total: 1.13 ms
Wall time: 1.64 ms
CPU times: user 535 µs, sys: 0 ns, total: 535 µs
Wall time: 539 µs
130.1841835762673


Почему методы ***numpy*** оказываются эффективнее?

In [ ]:
# Ваш ответ

## Дополнительные задачи

Дополнительные задачи подразумевают, что Вы самостоятельно разберётесь в некоторых функциях ***numpy***, чтобы их сделать, но в то же время не являются обязательными.

### Задача 4*

Дана функция двух переменных: $f(x, y) = sin(x)cos(y)$ (это просто такой красивый 3D-график), а также дана функция для отрисовки $f(x, y)$ (`draw_f()`), которая принимает на вход двумерную сетку, на которой будет вычисляться функция.  

Вам нужно разобраться в том, как строить такие сетки (подсказка - это одна конкретная функция ***numpy***), и подать такую сетку на вход функции отрисовки.

In [ ]:
from matplotlib import pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
%matplotlib inline

def f(x, y):
    '''Функция двух переменных'''
    return np.sin(x) * np.cos(y)

def draw_f(grid_x, grid_y):
    '''Функция отрисовки функции f(x, y)'''
    fig = plt.figure(figsize=(10, 8))
    ax = Axes3D(fig)
    ax.plot_surface(grid_x, grid_y, f(grid_x, grid_y), cmap='inferno')
    plt.show()

In [ ]:
grid_x, grid_y = # Ваш ответ

draw_f(grid_x, grid_y)

### Задача 5*

Вам дана картинка. При загрузке её размерность равна 3: **(w, h, num_channels)**, где **w** - ширина картинки в пикселях, **h** - высота картинки в пикселях, **num_channels** - количество каналов *(R, G, B, alpha)*.

Вам нужно "развернуть" картинку в одномерный массив размера w \* h \* num_channels, написав **одну строку кода**.

In [ ]:
from matplotlib import pyplot as plt
%matplotlib inline

Загрузим картинку. Если эта ячейка не сработает, смотрите дальше:

In [ ]:
path_to_image = './image.jpg'
image_array = plt.imread(path_to_image)

Если Вы работаете в google colab или по каким-то еще причинам картинка с диска не загрузилась, можно попробовать загрузить через ссылку в интернете:

In [ ]:
from PIL import Image
import requests
from io import BytesIO

path_to_image = '__enter your image URL here__'
# например: https://github.com/hocop/sberbank_madmo/raw/master/day_1/homework/image.jpg

response = requests.get(path_to_image)
img = Image.open(BytesIO(response.content))

image_array = np.array(img)

В любом случае, у Вас должен появиться объект `image_array`.  
Распечатаем его на экране:

In [ ]:
plt.imshow(image_array);

In [ ]:
# Ваш код здесь

In [ ]:
# Здесь выведите размерность нового массива